name: Add To GitHub Projects Beta

on:
  issues:
    types:
      - opened
jobs:
  add-to-project-backlog:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/Stoupe/projects/7
          github-token: ${{ secrets.GH_ACTIONS_ADD_TO_PROJECT_KEY }}
